### ISSUE TITLE
Preview can't be deactivated in the list of plugins

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-preview#51]
**Steps to reproduce**
open Geany
in the menu: Tools, Plugin Manager
search for Preview
deactivate Preview

**Result**
Geany is crashing

**System**
Lubuntu 23.10

**Comment by ralf3u** [comment]
Just for information:
The plugin Lua Script can be deactivated.

**Comment by xiota** [comment]
On my computer, using Geany 2.0, both plugins load and unload as expected.  Ubuntu 23.10 uses Geany 1.8, so may have a bug that has already been fixed.

**Comment by ralf3u** [comment]
So, I will test the issue with Lubuntu 24.04. Geany 2.0 should be part of it. I'll leave the issue open until then.

**Comment by xiota** [comment]
I am somewhat able to reproduce this now, but do not know the reason for the crash.

**Comment by xiota** [comment]
The problem seems to be that link-time optimization is now enabled by default.  There's a new build 0.0.7 in the PPA that should have it turned off.  Let me know if that fixes the crashing.

Looks like the PPA might have stay around a bit longer than I'd like...

* I tried [makedeb](https://github.com/makedeb/makedeb).  I like it a lot.  Much easier than traditional debian packaging.  But I forgot that building anything on debian requires installing lots of `-dev` packages.

* I also tried setting up a github workflow to make debs.  In [Actions](https://github.com/xiota/geany-preview/actions), you can see the successful jobs and download artifacts (buttom of the summary page for each completed job).  A problem is github is limited to LTS releases only.  Right now, 20.04 and 22.04.  Probably in several months, 24.04 will be added.  Also, they aren't automatically added to the releases page.

**Comment by ralf3u** [comment]
> Let me know if that fixes the crashing.

Now I can deactivate the plugin Preview in Geany 1.38.

**Comment by ralf3u** [comment]
That was today the answer in the terminal after an update:
```
W: Failed to fetch https://ppa.launchpadcontent.net/xiota/geany-plugins/ubuntu/dists/mantic/InRelease  Could not connect to ppa.launchpadcontent.net:443 (2620:2d:4000:1::81), connection timed out Could not connect to ppa.launchpadcontent.net:443 (185.125.190.80), connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by xiota** [comment]
Probably temporary connection problems.  Nothing I can do about it.  You can try downloading the files from the PPA webpage:

https://launchpad.net/~xiota/+archive/ubuntu/geany-plugins/+packages

**Comment by xiota** [comment]
Maybe servers under heavy load because close to 24.04 release.

**Comment by xiota** [comment]
@ralf3u  FYI, PPA is updated with following...

* Geany and Geany Plugins 2.0 for Ubuntu 20.04, 22.04, and 23.04.
* Plugins rebuilt, including for Ubuntu 24.04.

**Comment by ralf3u** [comment]
>Geany and Geany Plugins 2.0

I think that you mean Geany 2.0. Indeed now in Lubuntu 23.10 I can see that it is Geany 2.0. So, I will test switch-views in Geany 2.0 the next days in Lubuntu 23.10.

**Comment by ralf3u** [comment]
>PPA is updated with following ... Geany and Geany Plugins

Does that mean that I don't need to execute the following line in the terminal any more because when I install the PPA, there will be automatically Geany and Geany Plugins?
```
sudo apt install geany geany-plugins
```

**Comment by xiota** [comment]
I think `apt update ;  apt upgrade` should take care of it.
